### ISSUE TITLE
Homebrew package?

### ISSUE THREAD

**Issue by twe4ked** [numcommand/num#11]
Any plans/interest in a homebrew package?

**Comment by joelparkerhenderson** [comment]
Yes very much so. Would you like to do it? If so, I'll merge it.

**Comment by twe4ked** [comment]
What version would you see as being the canonical one? I'd assume we'd want the C one. We would also need it to be versioned to get into Homebrew.

**Comment by joelparkerhenderson** [comment]
The awk version because it's the most capable. I'll move the various implementations into their own repos now. Do you use IRC or some kind of chat? I'd be happy to chat about this if you like.

**Comment by twe4ked** [comment]
Ah, I thought the C version was feature compatible. I've decided to just use `fresh` [to install](https://github.com/twe4ked/dotfiles/commit/adc8c3c38218e23ce3b219f2185c79e9e745f71b) the awk version. Cheers.

**Comment by joelparkerhenderson** [comment]
Sounds good. I just made a bunch of updates to the repo, including a new URL to the install, so be sure you're getting the right item: I moved the command from ./num to ./bin/num.
