### ISSUE TITLE
Installing with curl results in "Permission denied"

### ISSUE THREAD

**Issue by brhumphe** [numcommand/num#4]
First, when running the curl command

```
curl -sSL https://raw.githubusercontent.com/numcommand/num/master/implementations/num-awk/num -o /usr/local/bin/num
```

as the local user, curl returns the error 

```
curl: (23) Failed writing body (0 != 15071)
```

I re-ran the command with `sudo`, which succeeded. But when I attempt to run `num`. I get the error `bash: /usr/local/bin/num: Permission denied`. I am running Crunchbangplusplus, which is essentially just Debian Jesse.

**Comment by joelparkerhenderson** [comment]
Can you try this and let me know if it works for you?
1. Instead of downloading to `/usr/local/bin/num`, download to `~/num`
   
   2.Then move it: `sudo mv ~/num /usr/local/bin/num`.

I'll update the README too.

**Comment by brhumphe** [comment]
Nope, that still results in the same permissions error. Other programs in
that directory run just fine without root privaliges.

**Comment by joelparkerhenderson** [comment]
Can you try this and let me know?

`sudo chmod +x /usr/local/bin/num`

The `num` program doesn't need to run with root privileges, and doesn't need to be in /usr/local/bin in particular. You can set the program as any user (for example `chown $USER num`) and put it anywhere (for example `~/num`). 

The program does need to be able to run `/bin/sh` and GNU `awk`.

**Comment by brhumphe** [comment]
Yep, that fixes it. Is there a way to set the +x flag in the repo itself?
Or is that just going to be a neccessary step of installation?

**Comment by joelparkerhenderson** [comment]
Good, thanks for trying it. The +x is already set in the repo. I'll look into how to make it happen better. Do you generally use a package manager, such as `apt` or `aptitude` or something else?

**Comment by brhumphe** [comment]
Yeah, either a package manager, .deb file, or install script of some
description.

**Comment by joelparkerhenderson** [comment]
Good. The `apt` package manager is on our list of longer-term goals. In the meantime, I'll look into how to make the current way smoother. May I close this issue now?

**Comment by brhumphe** [comment]
Yup; close it up.
