### ISSUE TITLE
Not working on Mac OS 10.11

### ISSUE THREAD

**Issue by soheilpro** [numcommand/num#5]
On Mac OS El Captain I get no result when running either of these commands:

```
echo "1 2 3 4" | num sum
echo "1 2 3 4" | num min
echo "1 2 3 4" | num max
```

Also, I get this error when I try avg:

```
> echo "1 2 3 4" | num avg
awk: division by zero
 source line number 1309
```

**Comment by joelparkerhenderson** [comment]
Thanks for posting. 

On Mac OS X, be sure you have a current `gawk` command, such as:

```
$ awk --version
GNU Awk 4.1.3, API: 1.1
```

If you need to install `gawk` here's one way to essentially replace the older OS X `awk` command with a current `gawk` command:

```
brew install gawk --default-names
```

Does that solve it for you?

Also, the Num roadmap includes a better install command for OS X. Do you have a preferred way of installing Mac software, such as by downloading, or MacPorts, or Homebrew, etc.?

**Comment by soheilpro** [comment]
I do have gawk `GNU Awk 4.1.3, API: 1.1` installed but it still is not working for me.

Homebrew is definitely the way to go for getting stuff installed on OS X, IMO.

**Comment by joelparkerhenderson** [comment]
Good. 

Can you try installing the current version, which has a bunch of improvements and fixes:

```
sudo curl -sSL https://raw.githubusercontent.com/numcommand/num/master/implementations/num-awk/num -o /usr/local/bin/num && sudo chmod +x /usr/local/bin/num
```

Verify the installation:

```
num --version
```

You should see Num version 1.0.0 or higher, and GNU Awk version 4.1.3 or higher.

```
Num version 1.0.0.
.... 
GNU Awk 4.1.3, API: 1.1
```

You should be able to run your commands now, such as:

```
echo "1 2 3 4" | num sum
```

I'll get an OS X El Cap machine today and try it too. Can you let me know what you find out?

**Comment by soheilpro** [comment]
The new version works though it seems my default is awk:

```
The system Awk command is:
/usr/bin/awk

awk version 20070501
```

Thanks anyways.

**Comment by jungle-boogie** [comment]
Hi @soheilpro,

That means its a path problem.

Do `whereis gawk` and then check your path with `echo $PATH` like such:
`% echo $PATH`
`/sbin:/bin:/usr/sbin:/usr/bin:/usr/games:/usr/local/sbin:/usr/local/bin:/home/vagrant/bin`

**Comment by joelparkerhenderson** [comment]
> The new version works though it seems my default is awk

Glad it works. Num looks for gawk first. Your setup will work fine.

I'll add an update to Num so it tells you exactly which gawk/awk is running. Thanks for the follow up.

**Comment by joelparkerhenderson** [comment]
Num now shows you which awk is running. If you intall the new Num, then run `num help`, you should see your Gawk path such as:

```
$ num help
Num version 1.2.1.
...
Num uses this Awk:
/usr/local/bin/gawk
....
GNU Awk 4.1.3, API: 1.1
```

**Comment by soheilpro** [comment]
@joelparkerhenderson Thanks man. Keep up the good work.
