### ISSUE TITLE
sum without scientific notation

### ISSUE THREAD

**Issue by jungle-boogie** [numcommand/num#6]
Hello,

Your tool is very amazing and its great that it's in shell because there's no compiling needed!
Thank you for writing it and maintaining it. Although it's not specific to awk, you may appreciate this project: https://github.com/johnkerl/miller/

`% gawk -F, '{print $10}' file.csv | num sum`
`5.7895e+06`

Is it possible to have the actual value printed without scientific notation?

Thanks!

**Comment by joelparkerhenderson** [comment]
Thanks! Miller looks excellent -- first time I've seen it.

I am creating a way for you to choose the output format. Please download the new Num today. Can you try it and let me know here if the new Num is working the way you want?

The output format enables you to print using decimals, floats, scientific notation, etc. and also control the precision and rounding.  To use the output format, set the OFMT environment variable.

Example to round numbers to two digits after the decimal point:

```
cat data | OFMT="%.2f" num sum 
```

**Comment by jungle-boogie** [comment]
Hello,

Sorry, I did not see this message from 5 days ago! I think if you edit the post, it may not show up in my feed so in the future, I'd recommend making a new post.

I'm now using num 1.2.0 and your ofmt trick works great.

Thanks!

Here it is working:

```
 % cat data | OFMT="%.2f" num sum
1795587.80
```
